server:
  port: 8084

keycloak:
  # turn off Spring-Boots Keycloak AutoConfiguration:
  # We only want to use Spring-Security without servlet container specific infrastructure.
  # This allows us to pull the Keycloak configuration from here instead of keycloak.json
  enabled: false

  realm: acme
  auth-server-url: http://sso.tdlabs.local:8899/u/auth
  # The client-id
  resource: app-frontend-springboot
  credentials:
    secret: 4822a740-20b9-4ff7-bbed-e664f4a70eb6
  ssl-required: external
  principal-attribute: preferred_username
  use-resource-role-mappings: true
  token-minimum-time-to-live: 30
#  client-keystore: ../../idm-system/keycloak/keycloak.jks
#  client-keystore-password: changeit